"""add warehouse and sales_daily

Revision ID: 6b0937a0e596
Revises: be0fe706b261
Create Date: 2025-09-29 08:14:14.138891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0937a0e596'
down_revision: Union[str, None] = 'be0fe706b261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ms_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ms_id')
    )
    op.create_table('sales_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('returns_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('receipts_count', sa.Integer(), nullable=False),
    sa.Column('inflow_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'warehouse_id', name='uq_sales_daily_date_wh')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_daily')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
